### ISSUE TITLE
Swarn

### ISSUE THREAD

**Issue by ardiadrianadri** [cryptovokins/dmusician#11]
## Descripción

Montar la integración de Swarn con la aplicación y dotarlo de datos de prueba (canciones, carátulas, banners)

**Comment by Steampunk1453** [comment]
Se han subido a Swarm las imagenes de las carátulas y de las empresas de los banners, junto con las canciones en formato en mp3. Las URLs están en el readme.

Se ha probado a desplegar el dist de la aplicación en Swarm y en IPFS y en ambos casos da un error 500. Se desplegara en Heroku
